Document: funk2
Title: Debian funk2 Manual
Author: <insert document author here>
Abstract: This manual describes what funk2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/funk2/funk2.sgml.gz

Format: postscript
Files: /usr/share/doc/funk2/funk2.ps.gz

Format: text
Files: /usr/share/doc/funk2/funk2.text.gz

Format: HTML
Index: /usr/share/doc/funk2/html/index.html
Files: /usr/share/doc/funk2/html/*.html
