LDFLAGS := $(EXTRA_LDFLAGS) -lrlutils -lrlagent -lrlgluenetdev
CFLAGS := $(EXTRA_CFLAGS) -Wall -pedantic 

all: BlocksWorldAgent

BlocksWorldAgent: blocks_world_agent.o 
	$(CC) blocks_world_agent.o $(LDFLAGS) -o BlocksWorldAgent      

blocks_world_agent.o: blocks_world_agent.c
	$(CC)  $(CFLAGS) -c blocks_world_agent.c -o blocks_world_agent.o 

clean:
	rm -rf BlocksWorldAgent.exe *.o









